### ISSUE TITLE
ToDo for ZCO74 Bieberleiche

### ISSUE THREAD

**Issue by F4BI** [F4BI/GermanCoopCommunityTemplate#4]
- [x] Player spawn dead
- [x] AI ignore disableAI in Init
- [ ] Convoy leave vehicles
- [ ] Waypoint sync to trigger dont work
- [ ] Mission description

**Comment by Pfandgiraffe** [comment]
1. behoben durch Benennung aller Marker (3 marker ohne Var name, dadurch der Bug!!! hat nur 3h gedauert den Fehler zu finden)
2. wird nicht ignoriert und funktioniert, verstehe den Sinn aber nicht da sich Soldaten nicht bewegen können. Empfehle die Soldaten einzeln zu setzen, also ohne Gruppe.
3. Liegt am Wegpunkt Typ. Keine Ahnung wie das seit Eden jetzt funzt. Probieren oder Forum...
4. Wenn das wirklich nicht geht (kein test) dann eben mit Variable arbeiten.
5. Was ist mit der description.ext?

**Comment by Pfandgiraffe** [comment]
p.s.: bekomme das wieder nicht hoch geladen. Brauche da eine Erklärung zu wie das mit dem 2. Brach funktioniert.
